name = "CVE-2017-16995"
type = "exploit"

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "16.04"
[supported_kernels.kernel]
version = [ 4 ]
major = [ 4 ]
minor = [ 0 ]
patch = [ 1, 116 ]

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "16.04"
[supported_kernels.kernel]
version = [ 4 ]
major = [ 8 ]
minor = [ 0 ]
patch = [ 1, 58 ]

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "16.04"
[supported_kernels.kernel]
version = [ 4 ]
major = [ 10 ]
minor = [ 0 ]
patch = [ 1, 42 ]

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "16.04"
[supported_kernels.kernel]
version = [ 4 ]
major = [ 11 ]
minor = [ 0 ]
patch = [ 1, 14 ]

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "16.04"
[supported_kernels.kernel]
version = [ 4 ]
major = [ 13 ]
minor = [ 0 ]
patch = [ 1, 21 ]
