name = "CVE-2017-1000112"
type = "exploit"

# TODO: the exploit also supports Ubuntu 14.04.

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "16.04"
release_mask = "4.4.0-(81|89)-.*"

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "16.04"
release_mask = "4.8.0-(34|36|39|41|45|46|49|51|52|53|54|56|58)-.*"
# 4.8.0-42 and 4.8.0-44 are missing from 34-58 range.

[mitigations]
disable_smap = true
