language: generic

os:
  - linux

dist:
  - bionic

addons:
  apt:
    packages:
    - qemu
  snaps:
    - name: go
      confinement: classic

services:
  - docker

env:
  - GO111MODULE=on

before_script:
  - go get -u code.dumpstack.io/tools/out-of-tree
  - sudo ln -s $HOME/.out-of-tree /root/
  - out-of-tree bootstrap

script:
  - sudo $(which out-of-tree) pack --autogen
  - |
    out-of-tree log query | grep FAILURE | while read line; do
        ID=$(echo $line | grep -o '[0-9]\+' | head -n 1)
        out-of-tree log dump $ID | tr -cd '\11\12\15\40-\176'
    done
  - out-of-tree log query
