language: generic

os:
  - linux

dist:
  - bionic

addons:
  apt:
    packages:
    - qemu
  snaps:
    - name: go
      confinement: classic

services:
  - docker

env:
  global:
    - GO111MODULE=on
  matrix:
    - EXPLOIT=CVE-2017-16995
    - EXPLOIT=CVE-2016-5195
    - EXPLOIT=CVE-2017-1000112

before_script:
  - go get -u code.dumpstack.io/tools/out-of-tree
  - sudo ln -s $HOME/.out-of-tree /root/
  - out-of-tree bootstrap
  - |
    cd $TRAVIS_BUILD_DIR/$EXPLOIT
    out-of-tree kernel autogen --max=8

script:
  - |
    cd $TRAVIS_BUILD_DIR/$EXPLOIT
    sudo $(which out-of-tree) pew --max=8
