language: go

go:
  - 1.x

os:
  - linux

dist:
  - bionic

addons:
  apt:
    packages:
    - qemu

services:
  - docker

env:
  global:
    - GO111MODULE=on
  matrix:
    - EXPLOIT=CVE-2017-16995
    - EXPLOIT=CVE-2016-5195
    - EXPLOIT=CVE-2017-1000112
    - EXPLOIT=CVE-2017-7308

before_script:
  - go get -u code.dumpstack.io/tools/out-of-tree
  - sudo ln -s $HOME/.out-of-tree /root/
  - |
    cd $TRAVIS_BUILD_DIR/$EXPLOIT
    out-of-tree kernel autogen --max=8

script:
  - |
    cd $TRAVIS_BUILD_DIR/$EXPLOIT
    sudo $(which out-of-tree) pew --runs=3 --timeout=20m --threshold=0.95
