name = "CVE-2016-5195"
type = "exploit"

# TODO: Add other major kernel versions

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "16.04"
[supported_kernels.kernel]
version = [ 4 ]
major = [ 4 ]
minor = [ 0 ]
patch = [ 0, 43 ]
